-- =========================================================================
-- dekdein. — Supabase schema STATUS (documentation only — no executable SQL)
--
-- ⚠️  THIS FILE DOES NOT CONTAIN THE PRODUCTION SCHEMA AND MUST NOT BE
--     TREATED AS ONE. Do not write or run any CREATE/ALTER/DROP statement
--     against Supabase based on this file. ⚠️
--
-- Why: the original prototype schema (table/trigger/RLS as first written
-- for this repo) has drifted from what's actually live in production.
-- Confirmed real differences, from the live database (not guessed):
--   - the name column on public.profiles is `name`, not `full_name`
--   - production also has is_customer, is_freelancer, availability_status,
--     phone_verified, identity_verified
--   - production has three additional functions: public.enable_freelancer(),
--     public.disable_freelancer(), public.enable_availability() — called
--     from app.js as zero-argument RPCs, assumed security definer / keyed
--     off auth.uid(), but their real bodies/signatures were never exported
--     into this repo
--   - handle_new_user()'s real current body is unknown; it must read
--     `name` (not `full_name`) from signup metadata since that's the real
--     column, but the exact SQL was never verified from this session
--
-- The original executable version of this schema (table/trigger/RLS as
-- first written, before any of the above was known) is kept for historical
-- reference only, in legacy-schema.sql — that file is marked
-- "DO NOT RUN AGAINST CURRENT PRODUCTION" for the same reason this one is.
--
-- How to get a real, trustworthy schema/migration file for this project:
--   1. Export the actual current schema from Supabase directly, e.g.
--      `supabase db dump --schema public` or the SQL Editor's schema
--      export, rather than reconstructing it from memory or from this repo.
--   2. Only once that export exists should a new schema.sql (or a proper
--      versioned migration) be written from it.
-- Until then, this file intentionally contains no CREATE/ALTER/DROP
-- statements, so it cannot be mistaken for something safe to run.
-- =========================================================================
